import { X, Sparkles, Loader2 } from 'lucide-react';

export default function AIBriefingModal({ workId, briefing, loading, error, onClose }) {
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-[var(--color-border-light)]">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center"
                 style={{ background: 'linear-gradient(135deg, #7c3aed, #a78bfa)' }}>
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">
                AI-Generated Briefing
              </h2>
              <p className="text-xs text-[var(--color-text-muted)]">
                Work Identifier: {workId}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg flex items-center justify-center hover:bg-[var(--color-background-alt)] transition-colors cursor-pointer"
            id="close-briefing-modal"
          >
            <X className="w-4 h-4 text-[var(--color-text-muted)]" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6">
          {loading && (
            <div className="flex flex-col items-center justify-center py-12 gap-3">
              <Loader2 className="w-8 h-8 text-[var(--color-brand)] animate-spin" />
              <p className="text-sm text-[var(--color-text-secondary)]">
                Generating intelligent analysis...
              </p>
            </div>
          )}
          {error && (
            <div className="p-4 rounded-xl text-sm" style={{ background: 'var(--color-critical-bg)', color: 'var(--color-critical)' }}>
              {error}
            </div>
          )}
          {!loading && !error && briefing && (
            <div className="animate-fade-in">
              <div className="p-5 rounded-xl bg-[var(--color-background)] border border-[var(--color-border-light)]">
                <p className="text-sm leading-relaxed text-[var(--color-text-primary)]">
                  {briefing}
                </p>
              </div>
              <p className="text-xs text-[var(--color-text-muted)] mt-4 text-center">
                This briefing was generated by Gemini based on engine findings.
                No personally identifiable information was transmitted.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
